#cicd for the ad-service microservice

name: ad-service

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/ad/**"

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with: 
        distribution: 'temurin'
        java-version: '21'
        cache: gradle
    
    - name: build with gradle and run tests
      run: |
        cd src/ad/
        ls -l
        ./gradlew clean build -x verifyGoogleJavaFormat

    - name: SonarCloud Scan
      run: ./gradlew sonarqube
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}