# CI for shipping application written in Rust 

name: shipping-ci

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy, rustfmt
    
    - name: code quality
      run: |
        cd src/shipping
        cargo clippy -- -D warnings

    - name: unit tests
      run: |
        cd src/shipping
        cargo test --verbose 

    - name: build
      run: |
        cd src/shipping
        cargo build --release

  Docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Copy proto file from pb 
      run: |
        cd pb/
        cp . /src/shipping/
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: src/shipping
        file: src/shipping/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/shipping:${{ github.run_id }}
        cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/shipping:cache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/shipping:cache,mode=max
  updateK8s:
    runs-on: ubuntu-latest
    needs: Docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update name in k8s deployment
      run: |
        sed -i "s|image: .*|image: ${{secrets.DOCKER_USERNAME}}/shipping:${{github.run_id}}|g" kubernetes/shipping/deploy.yaml

    - name: commit and push changes
      run: |
        git config --local user.email "sohamkanoj55@gmail.com"
        git config --local user.name "Soham Kanoj"
        git add .
        git commit -m "Update image tag to ${{secrets.DOCKER_USERNAME}}/shipping:${{github.run_id}}"
        git push origin main